### ISSUE TITLE
【依頼】　ChatSpace挙動確認

### ISSUE THREAD

**Issue by BouzuSuzuki** [BouzuSuzuki/chat-space#9]
# IPアドレス
18.177.218.187

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**ビューの崩れ**
文字の大きさや位置関係が仕様書と異なる部分があります。
検証で確認しながらpxの値などを変更し修正しましょう。

<img width="1439" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/84237970-4526ab80-ab35-11ea-9d81-4fd4847571c8.png">



お手本

<img width="1439" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/83826615-49a72a80-a717-11ea-9cb2-dc52a8f5c189.png">




参考カリキュラム:https://master.tech-camp.in/curriculums/3944
<img width="867" alt="ヘッダー" src="https://user-images.githubusercontent.com/44963290/84238119-7acb9480-ab35-11ea-955c-a286a2d6cfca.png">

<img width="862" alt="メッセージお手本" src="https://user-images.githubusercontent.com/44963290/83826711-8a06a880-a717-11ea-9403-8b349c098f21.png">




修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by BouzuSuzuki** [comment]
ビューの修正をしました。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by mo1015** [comment]
鈴木さん、ご提出ありがとうございます！
確認させていただきましたが全く問題ございませんでしたのでLGTMとさせていただきます！
すでにLGTM報告は完了しておりますので、再度提出いただかなくて大丈夫です🎉
おめでとうございます！！

**Comment by BouzuSuzuki** [comment]
ありがとうございました
